---
- name: GIT - Checking remote repository variable
  assert:
    that: ajgarlag_deploy_update_git_repo is defined

- name: GIT - Cloning remote repository to cache
  git:
    repo: "{{ ajgarlag_deploy_update_git_repo }}"
    dest: "{{ ajgarlag_deploy_path }}/repo"
    accept_hostkey: true
    bare: yes
  when: ajgarlag_deploy_update_git_cache

- name: GIT - Cloning cached repository to release path
  git:
    repo: "{{ ajgarlag_deploy_path }}/repo"
    dest: "{{ ajgarlag_deploy_path_release }}"
    version: "{{ ajgarlag_deploy_update_git_commit }}"
  when: ajgarlag_deploy_update_git_cache

- name: GIT - Cloning remote repository to release path
  git:
    repo: "{{ ajgarlag_deploy_update_git_repo }}"
    dest: "{{ ajgarlag_deploy_path_release }}"
    version: "{{ ajgarlag_deploy_update_git_commit }}"
  when: not ajgarlag_deploy_update_git_cache

- name: GIT - Creating 'deploy' branch
  command: git checkout -q -b deploy
  args:
    chdir: "{{ ajgarlag_deploy_path_release }}"

- name: GIT - Creating REVISION file
  shell: echo `git rev-parse HEAD` > REVISION
  args:
    chdir: "{{ ajgarlag_deploy_path_release }}"
